{% set name = "ttyd" %}
{% set version = "1.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tsl0922/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 039dd995229377caee919898b7bd54484accec3bba49c118e2d5cd6ec51e3650

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
    - pkg-config
  host:
    - json-c
    - libwebsockets
    - openssl
    - libuv
    - zlib
  run:
    - libuv

test:
  commands:
    - ttyd

about:
  home: http://github.com/tsl0922/ttyd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Share your terminal over the web

  dev_url: https://github.com/tsl0922/ttyd

extra:
  recipe-maintainers:
    - sodre
    - wolfv
