{% set name = "ttyd" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tsl0922/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c9cf5eece52d27c5d728000f11315d36cb400c6948d1964a34a7eae74b454099

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - cmake
    - pkg-config
  host:
    - json-c
    - libwebsockets
    - openssl
    - libuv
    - zlib
  run:
    - libuv

test:
  commands:
    - ttyd

about:
  home: http://github.com/tsl0922/ttyd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Share your terminal over the web

  dev_url: https://github.com/tsl0922/ttyd

extra:
  recipe-maintainers:
    - sodre
