{% set name = "ttyd" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tsl0922/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d72dcca3dec00cda87b80a0a25ae4fee2f8b9098c1cdb558508dcb14fbb6fafc

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - vim
  host:
    - json-c
    - libwebsockets
    - openssl
  run:
    - json-c

test:
  commands:
    - ttyd

about:
  home: http://github.com/tsl0922/ttyd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Share your terminal over the web

  dev_url: https://github.com/tsl0922/ttyd

extra:
  recipe-maintainers:
    - sodre
