{% set name = "ttyd" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tsl0922/{{ name }}/archive/{{ version }}.tar.gz
  sha256: edc44cd5319c0c9d0858081496cae36fc5c54ee7722e0a547dde39537dfb63de

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - cmake
    - pkg-config
  host:
    - json-c
    - libwebsockets
    - openssl
    - libuv
    - zlib
  run:
    - libuv

test:
  commands:
    - ttyd

about:
  home: http://github.com/tsl0922/ttyd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Share your terminal over the web

  dev_url: https://github.com/tsl0922/ttyd

extra:
  recipe-maintainers:
    - sodre
