context:
  name: ttyd
  version: "1.7.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/tsl0922/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 039dd995229377caee919898b7bd54484accec3bba49c118e2d5cd6ec51e3650
  patches:
    # backport of https://github.com/tsl0922/ttyd/pull/1502, needed to compile
    # with MSVC; only touches code behind _MSC_VER / MSVC guards
    - patches/0001-add-msvc-native-build-support-for-windows.patch

build:
  number: 3

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
    - cmake
    - pkg-config
  host:
    - json-c
    - libwebsockets
    - openssl
    - libuv
    - zlib
    # MSVC does not ship getopt.h
    - if: win
      then:
        - getopt-win32
  run:
    - libuv

tests:
  - script:
      - ttyd

about:
  homepage: https://github.com/tsl0922/ttyd
  license: MIT
  license_file: LICENSE
  summary: Share your terminal over the web
  repository: https://github.com/tsl0922/ttyd

extra:
  feedstock-name: ttyd
  recipe-maintainers:
    - sodre
    - wolfv
